- hosts: all
  roles:
    - role: geerlingguy.docker
    - role: install_docker_compose
    - role: deploy_app_python
      vars:
        docker_compose_src: ../../monitoring/docker-compose.yml
        promtail_src:       ../../monitoring/promtail.yml
