version: "3"

networks:
  loki:

volumes:
  app_data:

services:
  app_python:
    image: "danilag/app-python"
    volumes:
      - app_data:/app-python/data
    ports:
      - "6124:5000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        tag: "{{.ImageName}}"
    deploy:
      resources:
        limits:
          memory: 500M

  loki:
    image: "grafana/loki:2.5.0"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 500M

  promtail:
    image: "grafana/promtail:2.5.0"
    volumes:
      - /var/lib/docker/containers/:/var/lib/docker/containers
      - ./promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 500M

  prometheus:
    image: "prom/prometheus:v2.36.1"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 500M

  grafana:
    image: "grafana/grafana:9.0.0"
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 500M
