---

- name: Copy Docker-Compose
  copy:
    src: "{{ docker_compose_src }}"
    dest: tmp/
  copy:
    src: "{{ promtail_src }}"
    dest: tmp/

- name: Run Docker Compose
  docker_compose:
    project_src: tmp/
    state: present
